name: collegesafety
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.6.12
  firebase_messaging: ^15.2.10
  firebase_storage: ^12.4.10
  google_sign_in: ^6.2.1
  # workmanager: ^0.4.1  # Remove this problematic version

  # Notifications & Permissions
  flutter_local_notifications: ^17.2.1
  permission_handler: ^12.0.1
  vibration: ^2.0.0
  uuid: ^4.0.1
  intl: ^0.18.1
  percent_indicator: ^4.2.2
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png