// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_24lgrhLvJWwiWQATJSPkLNjE08aP0Ug',
    appId: '1:1056319177244:android:110019b357024f165e55d9',
    messagingSenderId: '1056319177244',
    projectId: 'nursing-safety-app',
    databaseURL: 'https://nursing-safety-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nursing-safety-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClhca0gjeaoofjTkI8kV5EcYtu9PmbtSo',
    appId: '1:1056319177244:ios:f8d14bbb8a6952225e55d9',
    messagingSenderId: '1056319177244',
    projectId: 'nursing-safety-app',
    databaseURL: 'https://nursing-safety-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nursing-safety-app.firebasestorage.app',
    iosClientId: '1056319177244-50ig7jbj4p5rcfj4rml694dtl819be49.apps.googleusercontent.com',
    iosBundleId: 'com.nursing.nursingcollege',
  );

}